#define UI_READY        "ready"
#define UI_SETTINGS     "Settings"
#define UI_BRIGHTNESS   "Brightness:"
#define UI_SWITCH_OFF   "Switch Off"
#define UI_NEW_GAME     "New Game"
#define UI_BACK         "Back"
#define UI_W_QUEENS     "w Queens"
#define UI_FLIP_BOARD   "Flip Board"
#define UI_CONNECTION   "Connection:"
#define UI_CHECK_PIECES "Check pieces!"

